version: '3.8'

services:
  budibase:
    image: budibase/budibase
    ports:
      - "10000:10000"
    environment:
      - COUCHDB_URL=http://couchdb:5984
      - REDIS_URL=redis://redis:6379
      - MINIO_URL=http://minio:9000
    depends_on:
      - couchdb
      - redis
      - minio

  couchdb:
    image: couchdb:3
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=tavonni
      - COUCHDB_PASSWORD=Fuckksjs808_

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    command: server /data
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=Fuckksjs808_
